### ISSUE TITLE
[Suggestion]关于软件包名

### ISSUE THREAD

**Issue by zxp19821005** [fzdwx/yakuza#15]
如题。
我目前已经将其移植到了ArchLinux的AUR，本来想用`launcher-bin`，但是太多的软件包都包含`launcher`了，所以暂时就移植为了`fzdwx-launcher-bin`(https://aur.archlinux.org/packages/fzdwx-launcher-bin)。不知道能不能改一下能够和其他软甲包直接区分的名字？
另：我的系统中已经中已经存在安装了`/usr/bin/ray`文件，属于包`mesa-demos`，第一次安装时失败了，我就直接使用系统自带的`ray`命令了，目前运行是正常的，不知道这个有没有什么影响？
OS: EndeavourOS
Kernel: 6.6.12-1-lts
DE: KDE Plasma 5.27.10

**Comment by fzdwx** [comment]
感谢！

关于软件名，我最近也在想，然后 `ray` 这个是必须的，我也考虑更名。

**Comment by fzdwx** [comment]
Hello, 现在我已经将项目重命名为 yakuza:

```
launcher -> yakuza
ray           -> yactrl
```

**Comment by zxp19821005** [comment]
好的，谢谢！
